# Generated by Django 5.0.6 on 2026-04-22 03:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=2)),
                ('bioma', models.CharField(max_length=20)),
                ('geometria', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('score_topsis', models.FloatField()),
                ('ranking', models.PositiveIntegerField()),
                ('nivel_risco', models.CharField(choices=[('CRITICO', 'Crítico'), ('ALTO', 'Alto'), ('MEDIO', 'Médio'), ('BAIXO', 'Baixo')], max_length=10)),
                ('total_focos', models.IntegerField(default=0)),
                ('frp_media', models.FloatField(default=0.0)),
                ('risco_historico_medio', models.FloatField(default=0.0)),
                ('vento_medio', models.FloatField(default=0.0)),
                ('ndvi_medio', models.FloatField(default=0.0)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='FocoQueimada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('data_hora', models.DateTimeField(db_index=True)),
                ('municipio', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('bioma', models.CharField(choices=[('AMAZONIA', 'Amazônia'), ('CERRADO', 'Cerrado'), ('CAATINGA', 'Caatinga'), ('MATA_ATLANTICA', 'Mata Atlântica'), ('PANTANAL', 'Pantanal'), ('PAMPA', 'Pampa')], max_length=20)),
                ('frp', models.FloatField(help_text='Fire Radiative Power em MW')),
                ('risco_historico', models.FloatField(default=0.0)),
                ('vento_ms', models.FloatField(blank=True, null=True)),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('satelite', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['bioma'], name='queimadas_f_bioma_7a48b7_idx'), models.Index(fields=['estado'], name='queimadas_f_estado_9ab156_idx'), models.Index(fields=['data_hora'], name='queimadas_f_data_ho_ec5a9e_idx')],
            },
        ),
    ]
