# Generated by Django 5.0.6 on 2026-04-22 04:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queimadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arearisco',
            name='geometria',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
