# Generated by Django 5.0.6 on 2026-04-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queimadas', '0002_alter_arearisco_geometria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arearisco',
            old_name='ndvi_medio',
            new_name='dias_sem_chuva_medio',
        ),
        migrations.RenameField(
            model_name='arearisco',
            old_name='vento_medio',
            new_name='precipitacao_media',
        ),
        migrations.RemoveField(
            model_name='focoqueimada',
            name='ndvi',
        ),
        migrations.RemoveField(
            model_name='focoqueimada',
            name='vento_ms',
        ),
        migrations.AddField(
            model_name='focoqueimada',
            name='dias_sem_chuva',
            field=models.FloatField(blank=True, help_text='Número de dias consecutivos sem chuva', null=True),
        ),
        migrations.AddField(
            model_name='focoqueimada',
            name='precipitacao',
            field=models.FloatField(blank=True, help_text='Precipitação acumulada em mm', null=True),
        ),
        migrations.AlterField(
            model_name='arearisco',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
